/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Creates a session and sets it in the configured session cookie.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session */
        get: operations["AuthController_getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service health */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a provider event */
        post: operations["ProviderEventsController_ingestProviderEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment references */
        get: operations["ReferencesController_listReferences"];
        put?: never;
        /** Create a payment reference */
        post: operations["ReferencesController_createReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a payment reference detail */
        get: operations["ReferencesController_getReferenceDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a payment reference */
        post: operations["ReferencesController_cancelReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginUserResponseDto: {
            id: string;
            username: string;
            /** @enum {string} */
            role: "OPERATOR" | "SUPERVISOR";
        };
        LoginSessionResponseDto: {
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            absoluteExpiresAt: string;
        };
        LoginResponseDto: {
            user: components["schemas"]["LoginUserResponseDto"];
            session: components["schemas"]["LoginSessionResponseDto"];
        };
        SessionResponseUserDto: {
            userId: string;
            username: string;
            /** @enum {string} */
            role: "OPERATOR" | "SUPERVISOR";
            sessionId: string;
        };
        SessionResponseDto: {
            user: components["schemas"]["SessionResponseUserDto"];
        };
        HealthChecksResponseDto: {
            /** @enum {string} */
            database: "up" | "down";
        };
        HealthResponseDto: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
            /** Format: date-time */
            timestamp: string;
            checks: components["schemas"]["HealthChecksResponseDto"];
        };
        ProviderCallbackDto: {
            providerEventId: string;
            referenceId: string;
            externalReference: string;
            /** @enum {string} */
            status: "PAID" | "CANCELLED";
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        ReferenceCreatorResponseDto: {
            id: string;
            username?: string;
            /** @enum {string} */
            role?: "OPERATOR" | "SUPERVISOR";
        };
        ReferenceResponseDto: {
            id: string;
            externalReference: string | null;
            concept: string;
            amount: number;
            currency: string;
            /** Format: date-time */
            dueDate: string;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "CANCELLED" | "EXPIRED";
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy: components["schemas"]["ReferenceCreatorResponseDto"];
        };
        ProviderEventResponseDto: {
            providerEventId: string;
            outcome: string;
            duplicate: boolean;
            reference: components["schemas"]["ReferenceResponseDto"];
        };
        CreateReferenceDto: {
            concept: string;
            amount: number;
            /** @example COP */
            currency: string;
            /** Format: date-time */
            dueDate: string;
        };
        ReferencePageInfoDto: {
            nextCursor: string | null;
        };
        ListReferencesResponseDto: {
            items: components["schemas"]["ReferenceResponseDto"][];
            pageInfo: components["schemas"]["ReferencePageInfoDto"];
        };
        ReferenceHistoryResponseDto: {
            id: string;
            /** @enum {string} */
            actorType: "USER" | "SYSTEM" | "PROVIDER";
            actorId: string | null;
            action: string;
            result: string;
            correlationId: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
        };
        ReferenceDetailResponseDto: {
            reference: components["schemas"]["ReferenceResponseDto"];
            history: components["schemas"]["ReferenceHistoryResponseDto"][];
        };
        CancelReferenceDto: {
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended and cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    ProviderEventsController_ingestProviderEvent: {
        parameters: {
            query?: never;
            header: {
                "x-provider-secret": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCallbackDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderEventResponseDto"];
                };
            };
        };
    };
    ReferencesController_listReferences: {
        parameters: {
            query?: {
                status?: "PENDING" | "PAID" | "CANCELLED" | "EXPIRED";
                createdFrom?: string;
                createdTo?: string;
                search?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListReferencesResponseDto"];
                };
            };
        };
    };
    ReferencesController_createReference: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReferenceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponseDto"];
                };
            };
        };
    };
    ReferencesController_getReferenceDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceDetailResponseDto"];
                };
            };
        };
    };
    ReferencesController_cancelReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelReferenceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponseDto"];
                };
            };
        };
    };
}
