export const AUDIT_ACTION = {
  CREATE_REFERENCE: 'CREATE_REFERENCE',
  IDEMPOTENT_REPLAY: 'IDEMPOTENT_REPLAY',
  CANCEL_ATTEMPT: 'CANCEL_ATTEMPT',
  CANCEL_REFERENCE: 'CANCEL_REFERENCE',
  EXPIRE_REFERENCE: 'EXPIRE_REFERENCE',
  PROVIDER_EVENT: 'PROVIDER_EVENT',
  PROVIDER_EVENT_REPLAY: 'PROVIDER_EVENT_REPLAY',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
