export const PROVIDER_EVENT_OUTCOME = {
  RECEIVED: 'RECEIVED',
  SUCCESS: 'SUCCESS',
  DUPLICATE: 'DUPLICATE',
  ACCEPTED_ALREADY_PAID: 'ACCEPTED_ALREADY_PAID',
  ACCEPTED_ALREADY_CANCELLED: 'ACCEPTED_ALREADY_CANCELLED',
  REJECTED_NOT_FOUND: 'REJECTED_NOT_FOUND',
  REJECTED_TERMINAL_STATE: 'REJECTED_TERMINAL_STATE',
  REJECTED_EXTERNAL_REFERENCE_CONFLICT: 'REJECTED_EXTERNAL_REFERENCE_CONFLICT',
  REJECTED_DUPLICATE_PAYLOAD_CONFLICT: 'REJECTED_DUPLICATE_PAYLOAD_CONFLICT',
} as const;

export type ProviderEventOutcome =
  (typeof PROVIDER_EVENT_OUTCOME)[keyof typeof PROVIDER_EVENT_OUTCOME];
